### ISSUE TITLE
Add flag to load environment without `export`

### ISSUE THREAD

**Issue by ultinous-kszegi** [tesujimath/nu_plugin_bash_env#10]
Hi!

Thanks for the work!
I may be knocking on the wrong door, as there could be a more efficient route to this.
But it's pretty common to load a .env file (e.g.: besides Dockerfile), or files like, God forbid /etc/os-release.

These doesn't contain the export builtin (or keyword?), so what is the correct way to load these to env?
I could envision a simple flag for this plugin, like `--greedy` or smth.[

**Comment by tesujimath** [comment]
So that's an interesting idea.  I understand why it would be useful.

I don't think it would be a good idea though to have a blanket option to export all shell variables as environment variables, as that could lead to environment pollution.

But I'm wondering whether an `--export` option would be useful, where you would list specific shell variables to be exported.  It would mean knowing which ones you expect, but I think you would in general?

Would that work for you?

**Comment by tesujimath** [comment]
This is done.  I like it.  Thanks for the suggestion @ultinous-kszegi :smile:

**Comment by ultinous-kszegi** [comment]
I realized I never did thank you for implementing that.
But I was reading the nushell documentation which does mention your plugin, and it did make me remember.

Thank you very much for considering, **and** implementing it!
